Traceback (most recent call last):
  File "/home/khan/Downloads/Xtr1.8_.01/Xtreme_InjectCrawler/XtremeWebAPP/run_crawler.py", line 4, in <module>
    from xtreme_server.models import *
  File "/home/khan/Downloads/Xtr1.8_.01/Xtreme_InjectCrawler/XtremeWebAPP/xtreme_server/models.py", line 3, in <module>
    class BlindProject(models.Model):
  File "/home/khan/miniconda3/lib/python3.7/site-packages/django/db/models/base.py", line 87, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/khan/miniconda3/lib/python3.7/site-packages/django/apps/registry.py", line 249, in get_containing_app_config
    self.check_apps_ready()
  File "/home/khan/miniconda3/lib/python3.7/site-packages/django/apps/registry.py", line 131, in check_apps_ready
    settings.INSTALLED_APPS
  File "/home/khan/miniconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/khan/miniconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/khan/miniconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/khan/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: bad magic number in 'XtremeWebAPP': b'\x03\xf3\r\n'
